services:
  app:
    build: ./react-nextjs-mongo
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./react-nextjs-mongo/src:/app/src
